# Generated by Django 4.0.3 on 2022-03-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shopservice_tailorshop_interested_and_more'),
        ('clothshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothshop',
            name='interested',
            field=models.CharField(choices=[('PO', 'POS'), ('Ad', 'Add shop online')], default=1, max_length=50, verbose_name='services'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clothshop',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='cloth_shops', to='shops.shopservice', verbose_name='services'),
        ),
    ]
