# Generated by Django 4.0.3 on 2022-03-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothshop', '0002_clothshop_interested_clothshop_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothshop',
            name='interested',
            field=models.CharField(choices=[('PO', 'POS'), ('Ad', 'Add shop online')], max_length=50, verbose_name='interested'),
        ),
    ]
