# Generated by Django 4.0.3 on 2022-03-28 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothshop', '0003_alter_clothshop_interested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothshop',
            name='disabled',
        ),
    ]
