# Generated by Django 4.0.3 on 2022-03-28 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TailorShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('logo', models.ImageField(null=True, upload_to='shops_logos/', verbose_name='logo')),
                ('address', models.TextField(verbose_name='address')),
                ('google_address', models.TextField(verbose_name='google_address')),
                ('latitude', models.CharField(max_length=100, verbose_name='latitude')),
                ('longitude', models.CharField(max_length=100, verbose_name='longitude')),
                ('category', models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('K', 'Kids'), ('A', 'All')], max_length=50, verbose_name='category')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('appointments_per_hour', models.IntegerField(default=0, verbose_name='appointments per hour')),
                ('approval_stage', models.CharField(choices=[('DP', 'Documents Pending'), ('DS', 'Documents Submited'), ('UR', 'Under Review'), ('A', 'Approved'), ('R', 'Rejected')], max_length=50, verbose_name='approval_stage')),
                ('application_status', models.CharField(max_length=255, verbose_name='application_status')),
                ('disabled', models.BooleanField(default=False, verbose_name='disabled')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='authentication.city', verbose_name='city')),
                ('employees', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='employees')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
        ),
        migrations.CreateModel(
            name='TailorTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('M', 'Monday'), ('TU', 'Tuesday'), ('W', 'Wednesday'), ('TH', 'Thursday'), ('F', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sunday')], max_length=50, verbose_name='day')),
                ('start_time', models.TimeField(verbose_name='start_time')),
                ('end_time', models.TimeField(verbose_name='end_time')),
            ],
        ),
        migrations.CreateModel(
            name='TailorShopBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='banners/', verbose_name='image')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='shops.tailorshop', verbose_name='shop')),
            ],
        ),
        migrations.CreateModel(
            name='TailorLegalDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card_front', models.ImageField(null=True, upload_to='id_cards/', verbose_name='id_card_front')),
                ('id_card_back', models.ImageField(null=True, upload_to='id_cards/', verbose_name='id_card_back')),
                ('commercial_license1', models.ImageField(null=True, upload_to='commercial_licenses/', verbose_name='commercial_license')),
                ('commercial_license2', models.ImageField(null=True, upload_to='commercial_licenses/', verbose_name='commercial_license')),
                ('signature', models.ImageField(null=True, upload_to='signatures/', verbose_name='signature')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_documents', to='shops.tailorshop', verbose_name='shop')),
            ],
        ),
        migrations.CreateModel(
            name='TailorFabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('article_number', models.CharField(max_length=255)),
                ('shades', models.CharField(max_length=255)),
                ('ref_no', models.CharField(max_length=255)),
                ('price_per_meter', models.IntegerField(default=0, verbose_name='price_per_meter')),
                ('image', models.ImageField(null=True, upload_to='fabrics/', verbose_name='logo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('made_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.country', verbose_name='country')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabrics', to='shops.tailorshop', verbose_name='shop')),
            ],
        ),
        migrations.CreateModel(
            name='TailorAppointmentLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50, verbose_name='location')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_locations', to='shops.tailorshop', verbose_name='shop')),
            ],
        ),
    ]
