# Generated by Django 4.0.3 on 2022-03-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopService',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'Alteration'), (2, 'New Stitching'), (3, 'Fabric'), (4, 'Ready Made')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='tailorshop',
            name='interested',
            field=models.CharField(choices=[('PO', 'POS'), ('Ad', 'Add shop online')], default=1, max_length=50, verbose_name='services'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tailorshop',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='shops', to='shops.shopservice', verbose_name='services'),
        ),
    ]
