# Generated by Django 4.0.3 on 2022-03-28 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('shops', '0002_shopservice_tailorshop_interested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailorshop',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='authentication.city', verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='tailorshop',
            name='interested',
            field=models.CharField(choices=[('PO', 'POS'), ('Ad', 'Add shop online')], max_length=50, verbose_name='interested'),
        ),
    ]
