# Generated by Django 4.0.3 on 2022-03-28 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_alter_tailorshop_city_alter_tailorshop_interested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tailorshop',
            name='disabled',
        ),
    ]
