# Generated by Django 4.0.3 on 2022-03-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_remove_tailorshop_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailorshop',
            name='delivery_location',
            field=models.CharField(default='home', max_length=255, verbose_name='delivery_location'),
            preserve_default=False,
        ),
    ]
