# Generated by Django 4.0.3 on 2022-03-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
